# Generated by Django 3.0.7 on 2020-07-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='music/img/avatar-3.jpg', null=True, upload_to='user'),
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
