# Generated by Django 3.0.7 on 2020-07-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200727_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user/avatar-3.jpg', null=True, upload_to='user'),
        ),
    ]
