# Generated by Django 3.0.7 on 2020-07-27 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('album_pic', models.ImageField(blank=True, upload_to='album')),
                ('release_year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('about', models.TextField(default=models.CharField(max_length=200, primary_key=True, serialize=False), max_length=400)),
                ('full_album', models.FileField(blank=True, upload_to='album zip')),
            ],
            options={
                'verbose_name_plural': 'Album',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('artist_pic', models.ImageField(blank=True, upload_to='artist')),
                ('about', models.TextField(blank=True, default='', max_length=400)),
            ],
            options={
                'verbose_name_plural': 'Artist',
                'ordering': ('artist_name',),
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('genre', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('song_pic', models.ImageField(blank=True, upload_to='song_pic')),
                ('song_file', models.FileField(blank=True, upload_to='song')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('artist', models.ManyToManyField(to='music.Artist')),
                ('genre', models.ManyToManyField(to='music.Genres')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Song',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comment',
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='Album_song',
            fields=[
                ('num', models.IntegerField(blank=True)),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('song_file', models.FileField(blank=True, upload_to='albumsong')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
                ('artist', models.ManyToManyField(related_name='album_songs', to='music.Artist')),
                ('genre', models.ManyToManyField(to='music.Genres')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Album_song',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(to='music.Genres'),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
