# Generated by Django 5.0 on 2023-12-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='genre',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
