# Generated by Django 5.0 on 2024-02-28 20:42

import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_album_views_alter_album_full_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_pic',
            field=models.ImageField(blank=True, default=music.models.get_default_album_image, upload_to='song_pic'),
        ),
    ]
