# Generated by Django 3.1 on 2022-05-13 20:38

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20220513_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_pic',
            field=models.ImageField(blank=True, default=music.models.get_default_album_image, upload_to=music.models.get_album_image_path),
        ),
    ]
